version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    command: npm run dev
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - DOCKER_URI=mongodb://mongo:27017/opendevbot_twitch
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - EVENTSUB_SECRET=${EVENTSUB_SECRET}
      - NODE_ENV=development
    depends_on:
      - mongo

volumes:
  mongo-data: {}
